### ISSUE TITLE
Question: possible to inject additional JS?

### ISSUE THREAD

**Issue by viglucci** [quorrajs/Ouch#10]
Is it possible to inject additional JS into the PrettyPageHandler ejs template?

When using technologies such as live-reload with gulp to watch server files, it would be nice to be able to provide an additional block of HTML as a string or provide a URL to that points to a JS file to the configuration objects to that the live reload script can be included on the page for automatic reload on server file change.

It currently looks like that in layout.ejs (https://github.com/quorrajs/Ouch/blob/master/resources/views/layout.ejs#L31) the block of JS read from (https://github.com/quorrajs/Ouch/blob/master/resources/js/ouch.base.js) is dumped onto the page. Would it be possible to dump a second block fo JS that is provided through configuration, or iterate an array of js file URL's to be included?

Thanks for your time

**Comment by harishanchu** [comment]
Hi @viglucci ,

As you already know right now it is not possible but we can upgrade `PrettyPageHandler` to accept a fifth param of additional JS file paths. This additional scripts can be injected to the `layout.ejs` as a second JS block or can be merged with the existing JS block itself.

I will work on it when I get some time or if you are interested in this I'm more than happy to accept the pull request  ;)

Thank you so much.

**Comment by viglucci** [comment]
I hope to submit a pull request for this sometime soon :).

**Comment by viglucci** [comment]
@harishanchu please see #13 at your convenience. Thanks!

**Comment by viglucci** [comment]
Closing this issue as #13 was merged over a year ago.
