### ISSUE TITLE
Possible implementation with Graphql?

### ISSUE THREAD

**Issue by wendelfreitas** [quorrajs/Ouch#18]
Hello

Any planning to implement handlers involving Graphql?

:heart: 

Best Regards!

**Comment by harishanchu** [comment]
Sorry, I didn't understand what you meant, could you please explain?

BTW ouch is a JS error handler which can be used to display any js error nicely in a web browser.

**Comment by wendelfreitas** [comment]
Sorry, I had a somewhat different thought, I thought of exception firing when queries and mutations are wrong, but that's already possible.
